# html rendering
PERFORMANCE_HEAD_TITLE = 'PERFORMANCE_HEAD_TITLE'
PERFORMANCE_REPORT_TITLE = 'PERFORMANCE_REPORT_TITLE'

# what is considered controllable
PERFORMANCE_CONTROLLABLE = 'PERFORMANCE_CONTROLLABLE'

# flight types to show
PERFORMANCE_LANES_FLIGHTTYPES = 'PERFORMANCE_LANES_FLIGHTTYPES'

# needs review, see performance.settings.contracts_use_date_range
PERFORMANCE_CONTRACTS_USE_DATE_RANGE = 'PERFORMANCE_CONTRACTS_USE_DATE_RANGE'

# date and time formats to use
DATEFMT = 'DATEFMT'
TIMEFMT = 'TIMEFMT'

# enable external import or update
PERFORMANCE_EXTERNAL_IMPORT = 'PERFORMANCE_EXTERNAL_IMPORT'
PERFORMANCE_EXTERNAL_UPDATE = 'PERFORMANCE_EXTERNAL_UPDATE'

# required for external query
PERFORMANCE_EXTERNAL_QUERY_CARRIER = 'PERFORMANCE_EXTERNAL_QUERY_CARRIER'
PERFORMANCE_EXTERNAL_QUERY_USAGE = 'PERFORMANCE_EXTERNAL_QUERY_USAGE'
KG_CONVERSION_FACTOR = 'KG_CONVERSION_FACTOR'

# disable showing multiple scheduled reports
SCHEDULED_REPORTS_ONLYONE = 'SCHEDULED_REPORTS_ONLYONE'

# Which performance stats to show.
PERFORMANCE_STATS = 'PERFORMANCE_STATS'
